project: 
  type: website

website: 
  page-navigation: true
  title: "Physics 312 - Advanced Mathematical Physics II" 
  site-url: "https://kennethmleo.github.io/Physics312/" 
  repo-url: "https://github.com/kennethmleo/Physics312"
  repo-actions: [edit, source, issue]
  favicon: images/favicon.ico
  
  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; CC-1.0"
  
  sidebar:
    background: "#D9E3E4"
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Home
      - href: content/language-model.qmd
        text: Language Models
      - href: content/diffusion.qmd
        text: Diffusion Models
      - href: content/hyperspectral_unmixing.qmd
        text: Hyperspectral Unmixing
      - href: content/report.qmd
        text: Report


format:
  html:
    theme:
      light: [cosmo, theme.scss] 
      dark: [cosmo, theme-dark.scss]
    code-copy: true
    code-overflow: wrap
    toc: true


filters:
  - include-files.lua
  - quarto

  
